// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOkojDppKh00EmIXX9PK3xajZkOmGGP7g',
    appId: '1:235908486305:web:963a64b7d77df21fb9cce0',
    messagingSenderId: '235908486305',
    projectId: 'goodhabitapp-7f20e',
    authDomain: 'goodhabitapp-7f20e.firebaseapp.com',
    storageBucket: 'goodhabitapp-7f20e.appspot.com',
    measurementId: 'G-ELJLVN9CB3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdZNNGzwlXIADSZ9gguUb-7JW0GLnQKf0',
    appId: '1:235908486305:android:6651074b443205c8b9cce0',
    messagingSenderId: '235908486305',
    projectId: 'goodhabitapp-7f20e',
    storageBucket: 'goodhabitapp-7f20e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZr2sSfUlE7YZu-K2pySoBINf7HwZs_f4',
    appId: '1:235908486305:ios:5fc0c0c89b76453bb9cce0',
    messagingSenderId: '235908486305',
    projectId: 'goodhabitapp-7f20e',
    storageBucket: 'goodhabitapp-7f20e.appspot.com',
    iosBundleId: 'com.example.goodHabitApp',
  );

}